import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsparser,
      parserOptions: { ecmaVersion: "latest", sourceType: "module" },
      globals: {
        chrome: "readonly",
        crypto: "readonly",
        indexedDB: "readonly",
        navigator: "readonly",
        document: "readonly",
        window: "readonly",
        history: "readonly",
        location: "readonly",
        btoa: "readonly",
        atob: "readonly",
        fetch: "readonly",
        Request: "readonly",
        Response: "readonly",
        Headers: "readonly",
        AbortController: "readonly",
        DOMException: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Blob: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        AbortSignal: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        requestAnimationFrame: "readonly",
        HTMLFormElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLElement: "readonly",
        HTMLIFrameElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        ParentNode: "readonly",
        ShadowRoot: "readonly",
        Event: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        InputEvent: "readonly",
        FormData: "readonly",
        CryptoKey: "readonly",
        IDBDatabase: "readonly",
        IDBTransactionMode: "readonly",
        IDBObjectStore: "readonly",
        IDBRequest: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Navigator: "readonly",
        React: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      "react-hooks": reactHooks,
    },
    rules: {
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "react-hooks/rules-of-hooks": "error",
    },
  },
];
